//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VenueMaker.Kwenda {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateAccountRequest", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
    [System.SerializableAttribute()]
    public partial class CreateAccountRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Organization {
            get {
                return this.OrganizationField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationField, value) != true)) {
                    this.OrganizationField = value;
                    this.RaisePropertyChanged("Organization");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateAccountResponse", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
    [System.SerializableAttribute()]
    public partial class CreateAccountResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VenueMaker.Kwenda.CreateAccountResponse.MethodResult ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VenueMaker.Kwenda.CreateAccountResponse.MethodResult Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="CreateAccountResponse.MethodResult", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
        public enum MethodResult : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Ok = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            UserAlreadyExists = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            RequiredInfoMissing = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            OtherError = 3,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerifyAccountRequest", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
    [System.SerializableAttribute()]
    public partial class VerifyAccountRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerifyAccountResponse", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
    [System.SerializableAttribute()]
    public partial class VerifyAccountResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VenueMaker.Kwenda.VerifyAccountResponse.MethodResult ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VenueMaker.Kwenda.VerifyAccountResponse.MethodResult Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="VerifyAccountResponse.MethodResult", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
        public enum MethodResult : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Ok = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NotFound = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            AlreadyUsed = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Expired = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            OtherError = 4,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateAccountRequest", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
    [System.SerializableAttribute()]
    public partial class UpdateAccountRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> InactiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Inactive {
            get {
                return this.InactiveField;
            }
            set {
                if ((this.InactiveField.Equals(value) != true)) {
                    this.InactiveField = value;
                    this.RaisePropertyChanged("Inactive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Organization {
            get {
                return this.OrganizationField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationField, value) != true)) {
                    this.OrganizationField = value;
                    this.RaisePropertyChanged("Organization");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateAccountResponse", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
    [System.SerializableAttribute()]
    public partial class UpdateAccountResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VenueMaker.Kwenda.UpdateAccountResponse.MethodResult ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VenueMaker.Kwenda.UpdateAccountResponse.MethodResult Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="UpdateAccountResponse.MethodResult", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
        public enum MethodResult : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Ok = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NotLoggedIn = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NotFound = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            OtherError = 3,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangePasswordRequest", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
    [System.SerializableAttribute()]
    public partial class ChangePasswordRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangePasswordResponse", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
    [System.SerializableAttribute()]
    public partial class ChangePasswordResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VenueMaker.Kwenda.ChangePasswordResponse.MethodResult ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VenueMaker.Kwenda.ChangePasswordResponse.MethodResult Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ChangePasswordResponse.MethodResult", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
        public enum MethodResult : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Ok = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            AccountNotFound = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            InvalidCode = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CodeAlreadyUsed = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CodeExpired = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            OtherError = 5,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginRequest", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
    [System.SerializableAttribute()]
    public partial class LoginRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppID {
            get {
                return this.AppIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AppIDField, value) != true)) {
                    this.AppIDField = value;
                    this.RaisePropertyChanged("AppID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResponse", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
    [System.SerializableAttribute()]
    public partial class LoginResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VenueMaker.Kwenda.LoginResponse.MethodResult ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VenueMaker.Kwenda.LoginResponse.MethodResult Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="LoginResponse.MethodResult", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
        public enum MethodResult : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Ok = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            InvalidCridentials = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            AccountInactive = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            AccountNotVerified = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            OtherError = 4,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogoutRequest", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
    [System.SerializableAttribute()]
    public partial class LogoutRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidateTokenRequest", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
    [System.SerializableAttribute()]
    public partial class ValidateTokenRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidateTokenResponse", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
    [System.SerializableAttribute()]
    public partial class ValidateTokenResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VenueMaker.Kwenda.ValidateTokenResponse.MethodResult ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VenueMaker.Kwenda.ValidateTokenResponse.MethodResult Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ValidateTokenResponse.MethodResult", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
        public enum MethodResult : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Ok = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Invalid = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Expired = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            OtherError = 3,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListKwendaFilesRequest", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
    [System.SerializableAttribute()]
    public partial class ListKwendaFilesRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NewerThanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NewerThan {
            get {
                return this.NewerThanField;
            }
            set {
                if ((this.NewerThanField.Equals(value) != true)) {
                    this.NewerThanField = value;
                    this.RaisePropertyChanged("NewerThan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListKwendaFilesResponse", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
    [System.SerializableAttribute()]
    public partial class ListKwendaFilesResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VenueMaker.Kwenda.KwendaFileListItem[] FilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VenueMaker.Kwenda.ListKwendaFilesResponse.MethodResult ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VenueMaker.Kwenda.KwendaFileListItem[] Files {
            get {
                return this.FilesField;
            }
            set {
                if ((object.ReferenceEquals(this.FilesField, value) != true)) {
                    this.FilesField = value;
                    this.RaisePropertyChanged("Files");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VenueMaker.Kwenda.ListKwendaFilesResponse.MethodResult Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ListKwendaFilesResponse.MethodResult", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
        public enum MethodResult : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Ok = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            OtherError = 1,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KwendaFileListItem", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
    [System.SerializableAttribute()]
    public partial class KwendaFileListItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileExtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VenueIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileExt {
            get {
                return this.FileExtField;
            }
            set {
                if ((object.ReferenceEquals(this.FileExtField, value) != true)) {
                    this.FileExtField = value;
                    this.RaisePropertyChanged("FileExt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileTitle {
            get {
                return this.FileTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.FileTitleField, value) != true)) {
                    this.FileTitleField = value;
                    this.RaisePropertyChanged("FileTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastModified {
            get {
                return this.LastModifiedField;
            }
            set {
                if ((this.LastModifiedField.Equals(value) != true)) {
                    this.LastModifiedField = value;
                    this.RaisePropertyChanged("LastModified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VenueId {
            get {
                return this.VenueIdField;
            }
            set {
                if ((object.ReferenceEquals(this.VenueIdField, value) != true)) {
                    this.VenueIdField = value;
                    this.RaisePropertyChanged("VenueId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetKwendaFileRequest", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
    [System.SerializableAttribute()]
    public partial class GetKwendaFileRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VenueMaker.Kwenda.KwendaFileId[] FileIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VenueMaker.Kwenda.KwendaFileId[] FileIds {
            get {
                return this.FileIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.FileIdsField, value) != true)) {
                    this.FileIdsField = value;
                    this.RaisePropertyChanged("FileIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KwendaFileId", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
    [System.SerializableAttribute()]
    public partial class KwendaFileId : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VenueIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VenueId {
            get {
                return this.VenueIdField;
            }
            set {
                if ((object.ReferenceEquals(this.VenueIdField, value) != true)) {
                    this.VenueIdField = value;
                    this.RaisePropertyChanged("VenueId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetKwendaFileResponse", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
    [System.SerializableAttribute()]
    public partial class GetKwendaFileResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VenueMaker.Kwenda.KwendaFileItem[] FilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VenueMaker.Kwenda.GetKwendaFileResponse.MethodResult ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VenueMaker.Kwenda.KwendaFileItem[] Files {
            get {
                return this.FilesField;
            }
            set {
                if ((object.ReferenceEquals(this.FilesField, value) != true)) {
                    this.FilesField = value;
                    this.RaisePropertyChanged("Files");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VenueMaker.Kwenda.GetKwendaFileResponse.MethodResult Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="GetKwendaFileResponse.MethodResult", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
        public enum MethodResult : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Ok = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            OtherError = 1,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KwendaFileItem", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
    [System.SerializableAttribute()]
    public partial class KwendaFileItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileExtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VenueIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileExt {
            get {
                return this.FileExtField;
            }
            set {
                if ((object.ReferenceEquals(this.FileExtField, value) != true)) {
                    this.FileExtField = value;
                    this.RaisePropertyChanged("FileExt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileTitle {
            get {
                return this.FileTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.FileTitleField, value) != true)) {
                    this.FileTitleField = value;
                    this.RaisePropertyChanged("FileTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastModified {
            get {
                return this.LastModifiedField;
            }
            set {
                if ((this.LastModifiedField.Equals(value) != true)) {
                    this.LastModifiedField = value;
                    this.RaisePropertyChanged("LastModified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VenueId {
            get {
                return this.VenueIdField;
            }
            set {
                if ((object.ReferenceEquals(this.VenueIdField, value) != true)) {
                    this.VenueIdField = value;
                    this.RaisePropertyChanged("VenueId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateKwendaFileRequest", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
    [System.SerializableAttribute()]
    public partial class UpdateKwendaFileRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VenueMaker.Kwenda.KwendaFileItem[] FilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InactivateAllForVenueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VenueMaker.Kwenda.KwendaFileItem[] Files {
            get {
                return this.FilesField;
            }
            set {
                if ((object.ReferenceEquals(this.FilesField, value) != true)) {
                    this.FilesField = value;
                    this.RaisePropertyChanged("Files");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InactivateAllForVenue {
            get {
                return this.InactivateAllForVenueField;
            }
            set {
                if ((this.InactivateAllForVenueField.Equals(value) != true)) {
                    this.InactivateAllForVenueField = value;
                    this.RaisePropertyChanged("InactivateAllForVenue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateKwendaFileResponse", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
    [System.SerializableAttribute()]
    public partial class UpdateKwendaFileResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VenueMaker.Kwenda.UpdateKwendaFileResponse.MethodResult ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VenueMaker.Kwenda.UpdateKwendaFileResponse.MethodResult Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="UpdateKwendaFileResponse.MethodResult", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
        public enum MethodResult : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Ok = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NotLoggedIn = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NoPermission = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            OtherError = 3,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetKwendaPermissionsRequest", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
    [System.SerializableAttribute()]
    public partial class SetKwendaPermissionsRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VenueMaker.Kwenda.KwendaPermissionItem[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VenueMaker.Kwenda.KwendaPermissionItem[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KwendaPermissionItem", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
    [System.SerializableAttribute()]
    public partial class KwendaPermissionItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GrantPermissionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ReadOnlyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VenueIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GrantPermission {
            get {
                return this.GrantPermissionField;
            }
            set {
                if ((this.GrantPermissionField.Equals(value) != true)) {
                    this.GrantPermissionField = value;
                    this.RaisePropertyChanged("GrantPermission");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReadOnly {
            get {
                return this.ReadOnlyField;
            }
            set {
                if ((this.ReadOnlyField.Equals(value) != true)) {
                    this.ReadOnlyField = value;
                    this.RaisePropertyChanged("ReadOnly");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VenueId {
            get {
                return this.VenueIdField;
            }
            set {
                if ((object.ReferenceEquals(this.VenueIdField, value) != true)) {
                    this.VenueIdField = value;
                    this.RaisePropertyChanged("VenueId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetKwendaPermissionsResponse", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
    [System.SerializableAttribute()]
    public partial class SetKwendaPermissionsResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VenueMaker.Kwenda.SetKwendaPermissionsResponse.MethodResult ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VenueMaker.Kwenda.SetKwendaPermissionsResponse.MethodResult Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="SetKwendaPermissionsResponse.MethodResult", Namespace="http://schemas.datacontract.org/2004/07/KwendaService.Models")]
        public enum MethodResult : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Ok = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NotLoggedIn = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NoPermission = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            OtherError = 3,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Kwenda.IKwendaService")]
    public interface IKwendaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKwendaService/Version", ReplyAction="http://tempuri.org/IKwendaService/VersionResponse")]
        string Version();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKwendaService/Version", ReplyAction="http://tempuri.org/IKwendaService/VersionResponse")]
        System.Threading.Tasks.Task<string> VersionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKwendaService/CreateAccount", ReplyAction="http://tempuri.org/IKwendaService/CreateAccountResponse")]
        VenueMaker.Kwenda.CreateAccountResponse CreateAccount(VenueMaker.Kwenda.CreateAccountRequest aInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKwendaService/CreateAccount", ReplyAction="http://tempuri.org/IKwendaService/CreateAccountResponse")]
        System.Threading.Tasks.Task<VenueMaker.Kwenda.CreateAccountResponse> CreateAccountAsync(VenueMaker.Kwenda.CreateAccountRequest aInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKwendaService/VerifyAccount", ReplyAction="http://tempuri.org/IKwendaService/VerifyAccountResponse")]
        VenueMaker.Kwenda.VerifyAccountResponse VerifyAccount(VenueMaker.Kwenda.VerifyAccountRequest aRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKwendaService/VerifyAccount", ReplyAction="http://tempuri.org/IKwendaService/VerifyAccountResponse")]
        System.Threading.Tasks.Task<VenueMaker.Kwenda.VerifyAccountResponse> VerifyAccountAsync(VenueMaker.Kwenda.VerifyAccountRequest aRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKwendaService/UpdateAccount", ReplyAction="http://tempuri.org/IKwendaService/UpdateAccountResponse")]
        VenueMaker.Kwenda.UpdateAccountResponse UpdateAccount(VenueMaker.Kwenda.UpdateAccountRequest aInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKwendaService/UpdateAccount", ReplyAction="http://tempuri.org/IKwendaService/UpdateAccountResponse")]
        System.Threading.Tasks.Task<VenueMaker.Kwenda.UpdateAccountResponse> UpdateAccountAsync(VenueMaker.Kwenda.UpdateAccountRequest aInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKwendaService/RequestVerificationCode", ReplyAction="http://tempuri.org/IKwendaService/RequestVerificationCodeResponse")]
        bool RequestVerificationCode(string aEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKwendaService/RequestVerificationCode", ReplyAction="http://tempuri.org/IKwendaService/RequestVerificationCodeResponse")]
        System.Threading.Tasks.Task<bool> RequestVerificationCodeAsync(string aEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKwendaService/ChangePassword", ReplyAction="http://tempuri.org/IKwendaService/ChangePasswordResponse")]
        VenueMaker.Kwenda.ChangePasswordResponse ChangePassword(VenueMaker.Kwenda.ChangePasswordRequest aInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKwendaService/ChangePassword", ReplyAction="http://tempuri.org/IKwendaService/ChangePasswordResponse")]
        System.Threading.Tasks.Task<VenueMaker.Kwenda.ChangePasswordResponse> ChangePasswordAsync(VenueMaker.Kwenda.ChangePasswordRequest aInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKwendaService/Login", ReplyAction="http://tempuri.org/IKwendaService/LoginResponse")]
        VenueMaker.Kwenda.LoginResponse Login(VenueMaker.Kwenda.LoginRequest aLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKwendaService/Login", ReplyAction="http://tempuri.org/IKwendaService/LoginResponse")]
        System.Threading.Tasks.Task<VenueMaker.Kwenda.LoginResponse> LoginAsync(VenueMaker.Kwenda.LoginRequest aLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKwendaService/Logout", ReplyAction="http://tempuri.org/IKwendaService/LogoutResponse")]
        bool Logout(VenueMaker.Kwenda.LogoutRequest aLogout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKwendaService/Logout", ReplyAction="http://tempuri.org/IKwendaService/LogoutResponse")]
        System.Threading.Tasks.Task<bool> LogoutAsync(VenueMaker.Kwenda.LogoutRequest aLogout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKwendaService/ValidateToken", ReplyAction="http://tempuri.org/IKwendaService/ValidateTokenResponse")]
        VenueMaker.Kwenda.ValidateTokenResponse ValidateToken(VenueMaker.Kwenda.ValidateTokenRequest aRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKwendaService/ValidateToken", ReplyAction="http://tempuri.org/IKwendaService/ValidateTokenResponse")]
        System.Threading.Tasks.Task<VenueMaker.Kwenda.ValidateTokenResponse> ValidateTokenAsync(VenueMaker.Kwenda.ValidateTokenRequest aRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKwendaService/ListKwendaFiles", ReplyAction="http://tempuri.org/IKwendaService/ListKwendaFilesResponse")]
        VenueMaker.Kwenda.ListKwendaFilesResponse ListKwendaFiles(VenueMaker.Kwenda.ListKwendaFilesRequest aRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKwendaService/ListKwendaFiles", ReplyAction="http://tempuri.org/IKwendaService/ListKwendaFilesResponse")]
        System.Threading.Tasks.Task<VenueMaker.Kwenda.ListKwendaFilesResponse> ListKwendaFilesAsync(VenueMaker.Kwenda.ListKwendaFilesRequest aRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKwendaService/GetKwendafiles", ReplyAction="http://tempuri.org/IKwendaService/GetKwendafilesResponse")]
        VenueMaker.Kwenda.GetKwendaFileResponse GetKwendafiles(VenueMaker.Kwenda.GetKwendaFileRequest aRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKwendaService/GetKwendafiles", ReplyAction="http://tempuri.org/IKwendaService/GetKwendafilesResponse")]
        System.Threading.Tasks.Task<VenueMaker.Kwenda.GetKwendaFileResponse> GetKwendafilesAsync(VenueMaker.Kwenda.GetKwendaFileRequest aRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKwendaService/UpdateKwendaFiles", ReplyAction="http://tempuri.org/IKwendaService/UpdateKwendaFilesResponse")]
        VenueMaker.Kwenda.UpdateKwendaFileResponse UpdateKwendaFiles(VenueMaker.Kwenda.UpdateKwendaFileRequest aRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKwendaService/UpdateKwendaFiles", ReplyAction="http://tempuri.org/IKwendaService/UpdateKwendaFilesResponse")]
        System.Threading.Tasks.Task<VenueMaker.Kwenda.UpdateKwendaFileResponse> UpdateKwendaFilesAsync(VenueMaker.Kwenda.UpdateKwendaFileRequest aRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKwendaService/SetKwendaPermissions", ReplyAction="http://tempuri.org/IKwendaService/SetKwendaPermissionsResponse")]
        VenueMaker.Kwenda.SetKwendaPermissionsResponse SetKwendaPermissions(VenueMaker.Kwenda.SetKwendaPermissionsRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKwendaService/SetKwendaPermissions", ReplyAction="http://tempuri.org/IKwendaService/SetKwendaPermissionsResponse")]
        System.Threading.Tasks.Task<VenueMaker.Kwenda.SetKwendaPermissionsResponse> SetKwendaPermissionsAsync(VenueMaker.Kwenda.SetKwendaPermissionsRequest req);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKwendaServiceChannel : VenueMaker.Kwenda.IKwendaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KwendaServiceClient : System.ServiceModel.ClientBase<VenueMaker.Kwenda.IKwendaService>, VenueMaker.Kwenda.IKwendaService {
        
        public KwendaServiceClient() {
        }
        
        public KwendaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KwendaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KwendaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KwendaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Version() {
            return base.Channel.Version();
        }
        
        public System.Threading.Tasks.Task<string> VersionAsync() {
            return base.Channel.VersionAsync();
        }
        
        public VenueMaker.Kwenda.CreateAccountResponse CreateAccount(VenueMaker.Kwenda.CreateAccountRequest aInfo) {
            return base.Channel.CreateAccount(aInfo);
        }
        
        public System.Threading.Tasks.Task<VenueMaker.Kwenda.CreateAccountResponse> CreateAccountAsync(VenueMaker.Kwenda.CreateAccountRequest aInfo) {
            return base.Channel.CreateAccountAsync(aInfo);
        }
        
        public VenueMaker.Kwenda.VerifyAccountResponse VerifyAccount(VenueMaker.Kwenda.VerifyAccountRequest aRequest) {
            return base.Channel.VerifyAccount(aRequest);
        }
        
        public System.Threading.Tasks.Task<VenueMaker.Kwenda.VerifyAccountResponse> VerifyAccountAsync(VenueMaker.Kwenda.VerifyAccountRequest aRequest) {
            return base.Channel.VerifyAccountAsync(aRequest);
        }
        
        public VenueMaker.Kwenda.UpdateAccountResponse UpdateAccount(VenueMaker.Kwenda.UpdateAccountRequest aInfo) {
            return base.Channel.UpdateAccount(aInfo);
        }
        
        public System.Threading.Tasks.Task<VenueMaker.Kwenda.UpdateAccountResponse> UpdateAccountAsync(VenueMaker.Kwenda.UpdateAccountRequest aInfo) {
            return base.Channel.UpdateAccountAsync(aInfo);
        }
        
        public bool RequestVerificationCode(string aEmail) {
            return base.Channel.RequestVerificationCode(aEmail);
        }
        
        public System.Threading.Tasks.Task<bool> RequestVerificationCodeAsync(string aEmail) {
            return base.Channel.RequestVerificationCodeAsync(aEmail);
        }
        
        public VenueMaker.Kwenda.ChangePasswordResponse ChangePassword(VenueMaker.Kwenda.ChangePasswordRequest aInfo) {
            return base.Channel.ChangePassword(aInfo);
        }
        
        public System.Threading.Tasks.Task<VenueMaker.Kwenda.ChangePasswordResponse> ChangePasswordAsync(VenueMaker.Kwenda.ChangePasswordRequest aInfo) {
            return base.Channel.ChangePasswordAsync(aInfo);
        }
        
        public VenueMaker.Kwenda.LoginResponse Login(VenueMaker.Kwenda.LoginRequest aLogin) {
            return base.Channel.Login(aLogin);
        }
        
        public System.Threading.Tasks.Task<VenueMaker.Kwenda.LoginResponse> LoginAsync(VenueMaker.Kwenda.LoginRequest aLogin) {
            return base.Channel.LoginAsync(aLogin);
        }
        
        public bool Logout(VenueMaker.Kwenda.LogoutRequest aLogout) {
            return base.Channel.Logout(aLogout);
        }
        
        public System.Threading.Tasks.Task<bool> LogoutAsync(VenueMaker.Kwenda.LogoutRequest aLogout) {
            return base.Channel.LogoutAsync(aLogout);
        }
        
        public VenueMaker.Kwenda.ValidateTokenResponse ValidateToken(VenueMaker.Kwenda.ValidateTokenRequest aRequest) {
            return base.Channel.ValidateToken(aRequest);
        }
        
        public System.Threading.Tasks.Task<VenueMaker.Kwenda.ValidateTokenResponse> ValidateTokenAsync(VenueMaker.Kwenda.ValidateTokenRequest aRequest) {
            return base.Channel.ValidateTokenAsync(aRequest);
        }
        
        public VenueMaker.Kwenda.ListKwendaFilesResponse ListKwendaFiles(VenueMaker.Kwenda.ListKwendaFilesRequest aRequest) {
            return base.Channel.ListKwendaFiles(aRequest);
        }
        
        public System.Threading.Tasks.Task<VenueMaker.Kwenda.ListKwendaFilesResponse> ListKwendaFilesAsync(VenueMaker.Kwenda.ListKwendaFilesRequest aRequest) {
            return base.Channel.ListKwendaFilesAsync(aRequest);
        }
        
        public VenueMaker.Kwenda.GetKwendaFileResponse GetKwendafiles(VenueMaker.Kwenda.GetKwendaFileRequest aRequest) {
            return base.Channel.GetKwendafiles(aRequest);
        }
        
        public System.Threading.Tasks.Task<VenueMaker.Kwenda.GetKwendaFileResponse> GetKwendafilesAsync(VenueMaker.Kwenda.GetKwendaFileRequest aRequest) {
            return base.Channel.GetKwendafilesAsync(aRequest);
        }
        
        public VenueMaker.Kwenda.UpdateKwendaFileResponse UpdateKwendaFiles(VenueMaker.Kwenda.UpdateKwendaFileRequest aRequest) {
            return base.Channel.UpdateKwendaFiles(aRequest);
        }
        
        public System.Threading.Tasks.Task<VenueMaker.Kwenda.UpdateKwendaFileResponse> UpdateKwendaFilesAsync(VenueMaker.Kwenda.UpdateKwendaFileRequest aRequest) {
            return base.Channel.UpdateKwendaFilesAsync(aRequest);
        }
        
        public VenueMaker.Kwenda.SetKwendaPermissionsResponse SetKwendaPermissions(VenueMaker.Kwenda.SetKwendaPermissionsRequest req) {
            return base.Channel.SetKwendaPermissions(req);
        }
        
        public System.Threading.Tasks.Task<VenueMaker.Kwenda.SetKwendaPermissionsResponse> SetKwendaPermissionsAsync(VenueMaker.Kwenda.SetKwendaPermissionsRequest req) {
            return base.Channel.SetKwendaPermissionsAsync(req);
        }
    }
}
